spring:
  kafka:
    address: localhost:9092
    consumer:
      bootstrap-servers: localhost:9092
      group-id: Messages
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer